spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres_user
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  quartz:
    dataSource:
      quartzDataSource:
        driver: org.postgresql.Driver
        URL: jdbc:postgresql://localhost:5430/postgres
        user: postgres_user
        password: 123456789
        maxConnections: 10
        provider: hikaricp
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    scheduler-name: trigger-quartz
    jobStore:
      dataSource: quartzDataSource
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceName: clusteredScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.jobStore.isClustered: true
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enable-idempotence: true
    listener:
      missing-topics-fatal: false


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
